apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9waWNrdXAtZ2FtZXM=  # mongodb://mongodb-service:27017/pickup-games
  jwt-secret: Y2hhbmdlLXRoaXMtdG8tYS1zZWN1cmUtc2VjcmV0  # change-this-to-a-secure-secret
  google-maps-api-key: eW91ci1nb29nbGUtbWFwcy1hcGkta2V5  # your-google-maps-api-key 